# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_276k7PcGwOByrRSdTT_iSltq8w_EPD5
"""

i=0
n=10
while i<n:
    print("Hello world", end=" ")
    i+=1