boston = datasets.load_boston()
boston_df = pd.DataFrame(boston['data'], columns=boston['feature_names'])
boston_df['PRICE'] = boston.target
print ("Columns: " + " ".join (boston_df.columns))

plt.plot (sorted(boston_df["PRICE"]), [x for _,x in sorted(zip(boston_df["CRIM"], boston_df["PRICE"]))])
plt.title ("You think this bad neighborhood?")
plt.xlabel ("Price")
plt.ylabel ("Crime")
plt.show()
plt.plot (sorted(boston_df["PRICE"]), [x for _,x in sorted(zip(boston_df["ZN"], boston_df["PRICE"]))])
plt.title ("You think this bad neighborhood?")
plt.xlabel ("Price")
plt.ylabel ("ZN")
plt.show ()
plt.plot (sorted(boston_df["PRICE"]), [x for _,x in sorted(zip(boston_df["INDUS"], boston_df["PRICE"]))])
plt.title ("You think this bad neighborhood?")
plt.xlabel ("Price")
plt.ylabel ("INDUS")
plt.show()
plt.plot (sorted(boston_df["PRICE"]), [x for _,x in sorted(zip(boston_df["CHAS"], boston_df["PRICE"]))])
plt.title ("You think this bad neighborhood?")
plt.xlabel ("Price")
plt.ylabel ("CHAS")
plt.show()
plt.plot (sorted(boston_df["PRICE"]), [x for _,x in sorted(zip(boston_df["NOX"], boston_df["PRICE"]))])
plt.title ("You think this bad neighborhood?")
plt.xlabel ("Price")
plt.ylabel ("NOX")
plt.show()
plt.plot (sorted(boston_df["PRICE"]), [x for _,x in sorted(zip(boston_df["RM"], boston_df["PRICE"]))])
plt.title ("You think this bad neighborhood?")
plt.xlabel ("Price")
plt.ylabel ("RM")
plt.show()
plt.plot (sorted(boston_df["PRICE"]), [x for _,x in sorted(zip(boston_df["AGE"], boston_df["PRICE"]))])
plt.title ("You think this bad neighborhood?")
plt.xlabel ("Price")
plt.ylabel ("AGE")
plt.show()
plt.plot (sorted(boston_df["PRICE"]), [x for _,x in sorted(zip(boston_df["DIS"], boston_df["PRICE"]))])
plt.title ("You think this bad neighborhood?")
plt.xlabel ("Price")
plt.ylabel ("DIS")
plt.show()
plt.plot (sorted(boston_df["PRICE"]), [x for _,x in sorted(zip(boston_df["RAD"], boston_df["PRICE"]))])
plt.title ("You think this bad neighborhood?")
plt.xlabel ("Price")
plt.ylabel ("RAD")
plt.show()
plt.plot (sorted(boston_df["PRICE"]), [x for _,x in sorted(zip(boston_df["TAX"], boston_df["PRICE"]))])
plt.title ("You think this bad neighborhood?")
plt.xlabel ("Price")
plt.ylabel ("TAX")
plt.show()
plt.plot (sorted(boston_df["PRICE"]), [x for _,x in sorted(zip(boston_df["PTRATIO"], boston_df["PRICE"]))])
plt.title ("You think this bad neighborhood?")
plt.xlabel ("Price")
plt.ylabel ("PTRATIO")
plt.show()
plt.plot (sorted(boston_df["PRICE"]), [x for _,x in sorted(zip(boston_df["B"], boston_df["PRICE"]))])
plt.title ("You think this bad neighborhood?")
plt.xlabel ("Price")
plt.ylabel ("B")
plt.show()
plt.plot (sorted(boston_df["LSTAT"]), [x for _,x in sorted(zip(boston_df["PRICE"], boston_df["LSTAT"]))])
plt.title ("You think this bad neighborhood?")
plt.xlabel ("LSTAT")
plt.ylabel ("Price")
plt.show()
